export const CENTER_COMPONENT_UNIT_LENGTH_RATIO = 0.1;
export const CENTER_COMPONENT_CIRCLE_RADIUS_RATIO = 150;
export const CENTER_COMPONENT_CIRCLE_THICKNESS_RATIO = 15;
export const CENTER_COMPONENT_LOADING_BAR_THICKNESS_RATIO = 4;