export const BLUR_LEVEL = Object.freeze({
    NONE: 0,
    EXTREMELY_LIGHT: 2,
    VERY_LIGHT: 4,
    LIGHT: 6,
    MEDIUM: 12,
    HEAVY: 18
});

export const INDEX = Object.freeze({
    SETTINGS_TABS_THEME: 0,
    SETTINGS_TABS_VIEW: 1,
    SETTINGS_TABS_PLAYGROUND: 2,
    SETTINGS_TABS_COLOR: 3,
    SETTINGS_TABS_SHAPE: 4,

    THEME_DARK: 0,
    THEME_BRIGHT: 1,
    THEME_YELLOW: 2,

    ENGINE_PART_FRONT: 1,
    ENGINE_PART_BACK: 0,
});

export const BASE_PANEL_MAX_ROTATION_DEGREE_VALUE = 5;
export const BASE_PANEL_MAX_TRANSLATE_PERCENTAGE_VALUE = 0;
export const NUMBER_OF_ENGINE_PART_SIDE_FACES = 8;